const COMPARING_WITH_ENEMY = "COMPARING_WITH_ENEMY";
const COMPARING_WITH_ENEMY_DETAIL = "COMPARING_WITH_ENEMY_DETAIL";
const LINE_WIN_OR_LOSE = "LINE_WIN_OR_LOSE";
const JANDI = "JANDI";
const SUMMONER = "SUMMONER";
const SPECTATOR = "SPECTATOR";
const MULTI_SEARCH = "MULTI_SEARCH";

const SUMMONER_FAIL = "SUMMONER_FAIL";
const SPECTATOR_FAIL = "SPECTATOR_FAIL";
const GAME_INFO_FAIL = "GAME_INFO_FAIL";
const MULTI_SEARCH_FAIL = "MULTI_SEARCH_FAIL";
const MATCH_DETAIL_FAIL = "MATCH_DETAIL_FAIL";
const REMOVE_RIOT_FAIL = "REMOVE_RIOT_FAIL";

export {
  COMPARING_WITH_ENEMY,
  COMPARING_WITH_ENEMY_DETAIL,
  JANDI,
  SUMMONER,
  SPECTATOR,
  MULTI_SEARCH,
  LINE_WIN_OR_LOSE,
  SUMMONER_FAIL,
  SPECTATOR_FAIL,
  GAME_INFO_FAIL,
  MULTI_SEARCH_FAIL,
  MATCH_DETAIL_FAIL,
  REMOVE_RIOT_FAIL,
};
