const COMPARING_WITH_ENEMY = "COMPARING_WITH_ENEMY";
const COMPARING_WITH_ENEMY_DETAIL = "COMPARING_WITH_ENEMY_DETAIL";
const LINE_WIN_OR_LOSE = "LINE_WIN_OR_LOSE";
const JANDI = "JANDI";
const SUMMONER = "SUMMONER";
const FAIL = "FAIL";

export { COMPARING_WITH_ENEMY, COMPARING_WITH_ENEMY_DETAIL, JANDI, SUMMONER, LINE_WIN_OR_LOSE, FAIL };
