const SUCCESS_MATCH_SUMMARY = "SUCCESS_MATCH_SUMMARY";
const SUCCESS_MATCH_SUMMARY_DETAIL = "SUCCESS_MATCH_SUMMARY_DETAIL";
const FAIL = "FAIL";

export { SUCCESS_MATCH_SUMMARY, SUCCESS_MATCH_SUMMARY_DETAIL, FAIL };
