const MATCH_SUMMARY = "MATCH_SUMMARY";
const MATCH_SUMMARY_DETAIL = "MATCH_SUMMARY_DETAIL";
const COMPARING_WITH_ENEMY = "COMPARING_WITH_ENEMY";
const COMPARING_WITH_ENEMY_DETAIL = "COMPARING_WITH_ENEMY_DETAIL";
const JANDI = "JANDI";
const FAIL = "FAIL";

export { MATCH_SUMMARY, MATCH_SUMMARY_DETAIL, COMPARING_WITH_ENEMY, COMPARING_WITH_ENEMY_DETAIL, JANDI, FAIL };
