const OAUTH_LOGIN = "OAUTH_LOGIN";
const OAUTH_LOGOUT = "OAUTH_LOGOUT";
const KAKAO = "KAKAO";
const NAVER = "NAVER";
const ACCESS_TOKEN = "ACCESS_TOKEN";
const REFRESH_TOKEN = "REFRESH_TOKEN";
const EXPIRES_IN = "EXPIRES_IN";
const OAUTH_TYPE = "OAUTH_TYPE";
const REISSUE_TOKEN = "REISSUE_TOKEN";
const VALID_TOKEN = "VALID_TOKEN";
const NON_EXISTENT_TOKEN = "NON_EXISTENT_TOKEN";
const EXPIRED_TOKEN = "EXPIRED_TOKEN";

export {
  OAUTH_LOGIN,
  OAUTH_LOGOUT,
  KAKAO,
  NAVER,
  ACCESS_TOKEN,
  REFRESH_TOKEN,
  EXPIRES_IN,
  OAUTH_TYPE,
  REISSUE_TOKEN,
  VALID_TOKEN,
  EXPIRED_TOKEN,
  NON_EXISTENT_TOKEN,
};
