// AUTH
const SIGN_UP = "SIGN_UP";
const SIGN_IN = "SIGN_IN";
const LOGOUT = "LOGOUT";

// TYPE
const SEARCH_MY_NAME = "searchMyName";
const KAKAO = "kakao";
const NAVER = "naver";

// TOKEN
const ACCESS_TOKEN = "ACCESS_TOKEN";
const ACCESS_TOKEN_EXPIRES_IN = "ACCESS_TOKEN_EXPIRES_IN";
const REFRESH_TOKEN = "REFRESH_TOKEN";
const REFRESH_TOKEN_EXPIRES_IN = "REFRESH_TOKEN_EXPIRES_IN";
const OAUTH_TYPE = "OAUTH_TYPE";

// TOKEN STATUS
const REISSUE_TOKEN = "REISSUE_TOKEN";
const VALID_TOKEN = "VALID_TOKEN";
const NON_EXISTENT_TOKEN = "NON_EXISTENT_TOKEN";
const EXPIRED_TOKEN = "EXPIRED_TOKEN";

// MY INFO
const MY_INFO = "MY_INFO";

export {
  SIGN_UP,
  SIGN_IN,
  LOGOUT,
  SEARCH_MY_NAME,
  KAKAO,
  NAVER,
  ACCESS_TOKEN,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN,
  REFRESH_TOKEN_EXPIRES_IN,
  OAUTH_TYPE,
  REISSUE_TOKEN,
  VALID_TOKEN,
  EXPIRED_TOKEN,
  NON_EXISTENT_TOKEN,
  MY_INFO,
};
