const RIOT = "RIOT";
const SUMMONER_INFO = "SUMMONER_INFO";
const SPECTATOR_INFO = "SPECTATOR_INFO";
const GAME_INFO = "GAME_INFO";
const MATCH_DETAIL = "MATCH_DETAIL";
const MULTI_SEARCH = "MULTI_SEARCH";

export { RIOT, SUMMONER_INFO, SPECTATOR_INFO, GAME_INFO, MATCH_DETAIL, MULTI_SEARCH };
