const ACCESS_TOKEN = "ACCESS_TOKEN";
const REFRESH_TOKEN = "REFRESH_TOKEN";
const ACCESS_TOKEN_EXPIRES_IN = "ACCESS_TOKEN_EXPIRES_IN";
const VALID_TOKEN = "VALID_TOKEN";
const REISSUE_TOKEN = "REISSUE_TOKEN";
const REFRESH_TOKEN_EXPIRES_IN = "REFRESH_TOKEN_EXPIRES_IN";
const NON_EXISTENT_TOKEN = "NON_EXISTENT_TOKEN";
const AUTH_TYPE = "AUTH_TYPE";
const FAIL = "FAIL";

export {
  ACCESS_TOKEN,
  REFRESH_TOKEN,
  VALID_TOKEN,
  ACCESS_TOKEN_EXPIRES_IN,
  REISSUE_TOKEN,
  REFRESH_TOKEN_EXPIRES_IN,
  NON_EXISTENT_TOKEN,
  AUTH_TYPE,
  FAIL,
};
